### PR TITLE
Converted arduino files to C++ as per platformio FAQs

### PR DESCRIPTION
**Pull request by fontanon**
Master branch as-is does not compiles with platformio as the _src/main.ino_ file is an Arduino file (not a cpp). Following the [platformio FAQ instructions](https://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually) I've successfully converted it into platformio format.

### CODE REVIEW

**Comment by kalanda** [comment]
Are you sure @fontanon? the master branch version of the project compiles without any issues in `platformio`. Either using `cli` as using IDE for Atom, as you can see in the screenshots below. Maybe you are missing something.

captura de pantalla 2019-01-15 a las 16 50 44
captura de pantalla 2019-01-15 a las 16 52 01

Is when you rename the `.ino` file to `.cpp` when it throws errors, due to lack of some needed includes such as `#include <Arduino.h>` as you can read in the instructions linked by you. (https://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually)

This pull request doesn't compiles for me.

**Comment by kalanda** [comment]
Closing here. Please reopen if I'm missing something.

**Comment by fontanon** [comment]
Hmm ... you're right it does compiles directly with platformio cli ... I tried from platformio for vscode and have a look at the image .. it recommended me to do the migration from .ino file to .cpp and add method prototypes as per the pull request. 

Warning on PlatformIO for VSCODE

I followed the recommendations here:
https://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually

**Comment by kalanda** [comment]
@fontanon that's why I rejected the PR. Your pull request only has one commit with the change of the filename, but nothing about the rest of the recommendations such as the "#include" of libraries and method prototypes. Check it out here https://github.com/kalanda/esp8266-sniffer/pull/11/files

Maybe you have some commits waiting to be pushed in your local repo :)

**Comment by fontanon** [comment]
You're right, there was a missing commit in my local repo :)
Thanks for invalidating this PR. I've opened a new one

**Pull request closed without merging**
